# -*- coding: utf-8 -*-
"""20220686.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ozik4LLo7XPKZsXbuNZqJxOaOKzybc0_

# **TA Session 2. Universal Adversarial Perturbation (UAP)**

<font color="#EE0000">!! Before starting this TA session, make sure to use GPU (T4) runtime !!</font>

## **1. Preperation**

### **1-1. Mount Your Google drive**
For UAP generation dataset and evaluation dataset, you have to mount your Google drive.
"""

# Mount your Google Drive!
# Do not change
# 로컬 서버 실행을 위해 Colab 드라이브 마운트 부분을 주석 처리합니다.
# from google.colab import drive
# drive.mount('/content/drive')

import os

# Check if Google Drive is successfully mounted
# 로컬 경로 확인용이 아니므로 주석 처리합니다.
# print(os.path.isdir("/content/drive/MyDrive/UAP/train_sub"))
# print(os.path.isdir("/content/drive/MyDrive/UAP/val_sub"))
# print(os.path.isfile("/content/drive/MyDrive/UAP/imagenet_labels.txt"))

# Code Cell 2
# Do not Change

# 실제 데이터셋(train_sub, val_sub 등)이 위치한 로컬 경로로 수정합니다.
# 현재 디렉토리에 데이터가 있다면 './' 를 사용합니다.
project_path = './' 
os.chdir(project_path)
print(f"working directory: {os.getcwd()}")

import torch
import torchvision
from torchvision.datasets import ImageFolder
from torchvision import transforms
from torch.utils.data import DataLoader
from tqdm import tqdm
import random

from basic_attack_core import apply_mi, apply_ti, apply_ni, apply_ni_decay, create_ti_conv, calculate_attack_ghat, update_mi_momentum
from evaluate import evaluate
import torch.nn.functional as F

random.seed=42

"""### **1-2. Dataset Load**

#### **Training Dataset**
In this practice section, we utilize subset of ImageNet training dataset, containing 1,000 images, one image per class.

#### **Validation Dataset**
We utilize subset of ImageNet validation dataset, containing 1,000 images, ones image per class.
"""

# Define Transformations For Preprocessing
transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor(),
])

normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])

# ImageNet Training Subset
dataset_train = ImageFolder(root='train_sub', transform=transform)
# ImageNet Validation Subset
dataset_val = ImageFolder(root='val_sub', transform=transform)

# Load datasets
train_loader = DataLoader(dataset_train, batch_size=8, shuffle=True)
val_loader = DataLoader(dataset_val, batch_size=32, shuffle=False)

"""### **1-3. Model Load**
In this TA session, we will use ResNet-50 as target model.
"""

model = torchvision.models.resnet50(pretrained=True)
model = model.to('cuda')
model.eval()

"""## **2. UAP Generation**

A single Universal Adversarial Perturbation (UAP) leads misinterpretation of model, when applied to any image.

In this TA session, you will generate a UAP using the **iterative Fast Gradient Sign Method (I-FGSM)** optimization on the ImageNet training dataset.

### **2-1. UAP Initialization**
"""

# UAP initialization
uap = torch.zeros((3, 224, 224)).to('cuda')
# For UAP update, set requires_grad True
uap.requires_grad = True

"""### **2-2. Hyperparameter initialization**

If you want to other UAP optimization techniques, feel free to add other hyperparameters you need.
"""

# hyperparameters for UAP generation (FGSM)
max_epsilon=12
step_size=0.7

"""### **2-3. SGD-UAP optimization**

In this practice section, **SGD-UAP** is utilized for UAP optimization.
For fast convergence, we will adopt I-FGSM-based optimization.

SGD-UAP with I-FGSM:

$\delta^{t+1} = \delta^{t} + \alpha\cdot\mathrm{Sign}\{∇_{\delta^t}(\frac{1}{|X_t|}\sum_{x \in X_t}J(x+\delta^t, y))\},$

$\delta^t = \mathrm{Clamp}_{\epsilon}(\delta^t),$

where $X_t$ is the image batch at $t$-th iteration, 
$J(x,y)$ is the loss functions with input image $x$ and label $y$. 
$\delta^t$ is the adversarial perturbation at $t$-th iteration. 
$\mathrm{Clamp}$ restricts the pixel value of the perturbation within the range of $[-\epsilon, \epsilon]$. 
$\alpha$ is the step size, which is a hyperparameter.

We will utilize cross entropy loss as the loss function.
"""

# for epoch in range(5):  # number of epochs
#     for i, data in tqdm(enumerate(train_loader), total=len(train_loader)):
#         inputs, labels = data
#         inputs = inputs.to('cuda')
#         labels = labels.to('cuda')

#         eps = max_epsilon / 255.0
#         alpha = step_size / 255.0

#         # =================== TODO 1 ======================
#         # Prepare adversarial inputs
#         # Add UAP to clean inputs
#         adv_inputs = inputs + uap.unsqueeze(0)
#         # clamp adversarial input with [0,1] range
#         adv_inputs = adv_inputs.clamp(0, 1)
#         # normalize input
#         adv_inputs = normalize(adv_inputs)
#         # ================================================


#         # =================== TODO 1 ======================
#         # Get adversarial model output
#         outputs = model(adv_inputs)
#         # Calculate loss
#         loss = F.cross_entropy(outputs, labels)
#         # ================================================


#         loss.backward()
#         grad = uap.grad.data

#         # =================== TODO 1 ======================
#         # Update UAP with FGSM
#         uap.data = uap.data + alpha * torch.sign(grad)
#         # clamp UAP with epsilon value
#         uap.data = uap.data.clamp(-eps, eps)
#         # ================================================

#         uap.grad.data.zero_()

"""### 2-4. Transferable UAP Generation

You can implement fature-level universal adversarial attack (**PG-UAP**) for transferability.

You can also apply MNI-DTS methods for transferability.

Please modify **basic_attack_core.py** file.
"""

# UAP initialization
uap_transfer = torch.zeros((3, 224, 224)).to('cuda')
# For UAP update, set requires_grad True
uap_transfer.requires_grad = True

# hyperparameters for UAP generation (FGSM)
max_epsilon=12
step_size=0.7

# Hyperparameter tuning
# ======================= TODO 8 =======================
attack_type = "MNDTS" 
mu = 1.0
number_of_si_scales = 10  # SI 끄기
di_prob = 0.9          
di_pad_amount = 31
di_pad_value = 0
ti_kernel_size = 5
feature_attack = True    # 대망의 Feature Attack 활성화!
depth = 'layer3'         # (Tip: 'layer3'로 바꿔보는 것도 전이성에 큰 도움이 될 수 있습니다)
# ======================================================

target_label = -1

for epoch in range(7):  # number of epochs
    g = 0
    for i, data in tqdm(enumerate(train_loader), total=len(train_loader)):
        inputs, labels = data
        inputs = inputs.to('cuda')
        labels = labels.to('cuda')

        mu = max(apply_mi(attack_type, mu), apply_ni_decay(attack_type, mu))

        ti_conv = None
        if 'T' in attack_type:  # Create smoothing kernel for translation-invariance.
            ti_conv = create_ti_conv(inputs.device, ti_kernel_size)

        model.eval()

        eps = max_epsilon / 255.0  # epsilon in scale [0, 1]
        alpha = step_size / 255.0   # alpha in scale [0, 1]

        x_adv = inputs + uap_transfer.unsqueeze(0)
        x_adv = normalize(x_adv.clamp(0, 1))
        x_clean = normalize(inputs)

        # Calculate ghat from the current adversarial point.
        x_adv_or_nes = apply_ni(attack_type, x_adv, alpha, mu, g)

        ghat = calculate_attack_ghat(model, x_adv_or_nes, labels, number_of_si_scales, target_label, attack_type,
                                    di_prob, di_pad_amount, di_pad_value, feature_attack, x_clean, depth)

        # Update g (momentum accumulator)
        ghat = apply_ti(ghat, attack_type, ti_conv)
        g = update_mi_momentum(g, ghat, mu)

        # Batch mean of gradient
        g = torch.mean(g, dim=0)

        # Update uap
        pert = alpha * g.sign()
        uap_transfer = uap_transfer + pert

        uap_transfer.data = uap_transfer.data.clamp(-eps, eps)

"""## **3. White-box Evaluation**

### **3-1. Evaluation for Clean Data**
"""

# correct = 0
# total = 0

# for i, data in tqdm(enumerate(val_loader), total=len(val_loader)):
#     inputs, labels = data
#     inputs = inputs.to('cuda')
#     labels = labels.to('cuda')

#     inputs = normalize(inputs)

#     outputs = model(inputs)
#     predicted = torch.argmax(outputs.data, dim=1)
#     total += labels.size(0)
#     correct += (predicted == labels).sum().item()

# print('Accuracy of the model on clean validation images: {} %'.format(100 * correct / total))

"""### **3-2. Evaluation for Random Noise**

For a fair comparison, we define a random noise with pixel value within the range $[-\epsilon, \epsilon]$.
"""

# correct = 0
# total = 0

# # Define Random noise with pixel value [-eps, eps]
# random_noise = (torch.rand_like(uap) * 2 - 1) * eps


# for i, data in tqdm(enumerate(val_loader), total=len(val_loader)):
#     inputs, labels = data
#     inputs = inputs.to('cuda')
#     labels = labels.to('cuda')


#     # Prepare adversarial inputs
#     # Add UAP to clean inputs
#     adv_inputs_random = inputs + random_noise.unsqueeze(0)
#     # clamp adversarial inputs within [0,1] range
#     adv_inputs_random = adv_inputs_random.clamp(0, 1)
#     # normalize adversarial input
#     adv_inputs_random = normalize(adv_inputs_random)

#     outputs = model(adv_inputs_random)
#     predicted = torch.argmax(outputs.data, dim=1)
#     total += labels.size(0)
#     correct += (predicted == labels).sum().item()

# asr = 100*(1-(correct/total))
# print(f'Attack Success Rate: {asr}%')

"""### **3-3. Evaluation for SGD-UAP**"""

# correct=0
# total=0

# for i, data in tqdm(enumerate(val_loader), total=len(val_loader)):

#     inputs, labels = data
#     inputs = inputs.to('cuda')
#     labels = labels.to('cuda')


#     # Prepare adversarial inputs
#     # Add UAP to clean inputs
#     adv_inputs = inputs + uap.unsqueeze(0)
#     # clamp adversarial inputs within [0,1] range
#     adv_inputs = adv_inputs.clamp(0, 1)
#     # normalize adversarial input
#     adv_inputs = normalize(adv_inputs)


#     outputs = model(adv_inputs)
#     predicted = F.softmax(outputs.data, dim=1).max(dim=1)
#     # print(predicted)

#     total += labels.size(0)
#     correct += torch.sum((predicted[1] == labels).float()).item()

# asr = 100*(1-(correct/total))
# print(f'Attack Success Rate: {asr}%')

"""### **3-4. Evaluation for transferable UAP (whitebox)**"""

# correct=0
# total=0

# for i, data in tqdm(enumerate(val_loader), total=len(val_loader)):

#     inputs, labels = data
#     inputs = inputs.to('cuda')
#     labels = labels.to('cuda')


#     # Prepare adversarial inputs
#     # Add UAP to clean inputs
#     adv_inputs = inputs + uap_transfer.unsqueeze(0)
#     # clamp adversarial inputs within [0,1] range
#     adv_inputs = adv_inputs.clamp(0, 1)
#     # normalize adversarial input
#     adv_inputs = normalize(adv_inputs)


#     outputs = model(adv_inputs)
#     predicted = F.softmax(outputs.data, dim=1).max(dim=1)
#     # print(predicted)

#     total += labels.size(0)
#     correct += torch.sum((predicted[1] == labels).float()).item()

# asr = 100*(1-(correct/total))
# print(f'Attack Success Rate: {asr}%')

"""## **4. Visualization**

### 4-1. UAP Visualization
"""

# import matplotlib.pyplot as plt

# # Rescale uap [-eps, eps] to [0,1]
# uap_vis = (uap + eps) / (eps * 2)
# uap_vis = uap_vis.detach().cpu().permute(1, 2, 0).numpy()

# uap_transfer_vis = (uap_transfer + eps) / (eps * 2)
# uap_transfer_vis = uap_transfer_vis.detach().cpu().permute(1, 2, 0).numpy()

# fig, axes = plt.subplots(1, 2, figsize=(10, 4))

# axes[0].imshow(uap_vis)
# axes[0].set_title('SGD-UAP')
# axes[0].axis('off')

# axes[1].imshow(uap_transfer_vis)
# axes[1].set_title('Transferable UAP')
# axes[1].axis('off')

# plt.tight_layout()
# plt.show()

# """### 4-2. Model Prediction Visualization"""

# # Numerical label to text label for visualization
# def read_txt_to_dict(file_path):
#     my_dict = {}
#     with open(file_path, 'r', encoding='utf-8') as file:
#         for line in file:
#             line = line.strip()
#             line = line.strip('{')
#             line = line.strip('}')
#             if line:
#                 key_value = line.split(': ', 1)
#                 key = int(key_value[0])
#                 value = key_value[1].strip().rstrip(",").strip("'")
#                 my_dict[key] = value
#     return my_dict

# # imagenet_labels_dict = read_txt_to_dict('/content/drive/MyDrive/UAP_dataset/imagenet_labels.txt')
# imagenet_labels_dict = read_txt_to_dict('imagenet_labels.txt')

# import matplotlib.pyplot as plt

# random_index = random.randint(0, len(val_loader))
# data = val_loader.dataset[random_index]

# inputs, labels = data
# inputs = inputs.to('cuda')
# inputs = inputs.unsqueeze(0)

# input_norm = normalize(inputs)
# clean_output = model(input_norm)
# clean_predicted = torch.argmax(clean_output.data, dim=1)

# adv_input_random = inputs + random_noise.unsqueeze(0)
# adv_input_random = adv_input_random.clamp(0, 1)
# adv_input_random_norm = normalize(adv_input_random)

# adv_input = inputs + uap.unsqueeze(0)
# adv_input = adv_input.clamp(0, 1)
# adv_input_norm = normalize(adv_input)

# # uap_transfer
# adv_input_transfer = inputs + uap_transfer.unsqueeze(0)
# adv_input_transfer = adv_input_transfer.clamp(0, 1)
# adv_input_transfer_norm = normalize(adv_input_transfer)

# adv_random_output = model(adv_input_random_norm)
# adv_random_predicted = torch.argmax(adv_random_output.data, dim=1)

# adv_output = model(adv_input_norm)
# adv_predicted = torch.argmax(adv_output.data, dim=1)

# adv_transfer_output = model(adv_input_transfer_norm)
# adv_transfer_predicted = torch.argmax(adv_transfer_output.data, dim=1)

# fig, axes = plt.subplots(1, 4, figsize=(24, 5))

# axes[0].imshow(inputs[0].detach().cpu().permute(1, 2, 0).numpy())
# axes[0].set_title(f"Clean: {imagenet_labels_dict[clean_predicted[0].item()]}", wrap=True)
# axes[0].axis("off")

# axes[1].imshow(adv_input_random[0].detach().cpu().permute(1, 2, 0).numpy())
# axes[1].set_title(f"Random Noise: {imagenet_labels_dict[adv_random_predicted[0].item()]}", wrap=True)
# axes[1].axis("off")

# axes[2].imshow(adv_input[0].detach().cpu().permute(1, 2, 0).numpy())
# axes[2].set_title(f"SGD-UAP: {imagenet_labels_dict[adv_predicted[0].item()]}", wrap=True)
# axes[2].axis("off")

# axes[3].imshow(adv_input_transfer[0].detach().cpu().permute(1, 2, 0).numpy())
# axes[3].set_title(f"Transferable UAP: {imagenet_labels_dict[adv_transfer_predicted[0].item()]}", wrap=True)
# axes[3].axis("off")

# plt.show()

"""## **5. Black-box Evalution**

### **5-1. SGD-UAP black-box evaluation**
"""

# evaluate(dataset_val, val_loader, uap)

"""### **5-2. Transferable UAP black-box evaluation**"""

evaluate(dataset_val, val_loader, uap_transfer)