# -*- coding: utf-8 -*-
"""20220686.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ozik4LLo7XPKZsXbuNZqJxOaOKzybc0_

# **TA Session 2. Universal Adversarial Perturbation (UAP)**

<font color="#EE0000">!! Before starting this TA session, make sure to use GPU (T4) runtime !!</font>

## **1. Preperation**

### **1-1. Mount Your Google drive**
For UAP generation dataset and evaluation dataset, you have to mount your Google drive.
"""

# Mount your Google Drive!
# Do not change
# 로컬 서버 실행을 위해 Colab 드라이브 마운트 부분을 주석 처리합니다.
# from google.colab import drive
# drive.mount('/content/drive')

import os

# Check if Google Drive is successfully mounted
# 로컬 경로 확인용이 아니므로 주석 처리합니다.
# print(os.path.isdir("/content/drive/MyDrive/UAP/train_sub"))
# print(os.path.isdir("/content/drive/MyDrive/UAP/val_sub"))
# print(os.path.isfile("/content/drive/MyDrive/UAP/imagenet_labels.txt"))

# Code Cell 2
# Do not Change

# 실제 데이터셋(train_sub, val_sub 등)이 위치한 로컬 경로로 수정합니다.
# 현재 디렉토리에 데이터가 있다면 './' 를 사용합니다.
project_path = './' 
os.chdir(project_path)
print(f"working directory: {os.getcwd()}")

import torch
import torchvision
from torchvision.datasets import ImageFolder
from torchvision import transforms
from torch.utils.data import DataLoader
from tqdm import tqdm
import random

from basic_attack_core import apply_mi, apply_ti, apply_ni, apply_ni_decay, create_ti_conv, calculate_attack_ghat, update_mi_momentum
from evaluate import evaluate
import torch.nn.functional as F

random.seed=42

"""### **1-2. Dataset Load**

#### **Training Dataset**
In this practice section, we utilize subset of ImageNet training dataset, containing 1,000 images, one image per class.

#### **Validation Dataset**
We utilize subset of ImageNet validation dataset, containing 1,000 images, ones image per class.
"""

# Define Transformations For Preprocessing
transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor(),
])

normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])

# ImageNet Training Subset
dataset_train = ImageFolder(root='train_sub', transform=transform)
# ImageNet Validation Subset
dataset_val = ImageFolder(root='val_sub', transform=transform)

# Load datasets
train_loader = DataLoader(dataset_train, batch_size=8, shuffle=True)
val_loader = DataLoader(dataset_val, batch_size=32, shuffle=False)

"""### **1-3. Model Load**
In this TA session, we will use ResNet-50 as target model.
"""

model = torchvision.models.resnet50(pretrained=True)
model = model.to('cuda')
model.eval()

"""## **2. UAP Generation**

A single Universal Adversarial Perturbation (UAP) leads misinterpretation of model, when applied to any image.

In this TA session, you will generate a UAP using the **iterative Fast Gradient Sign Method (I-FGSM)** optimization on the ImageNet training dataset.

### **2-1. UAP Initialization**
"""

# UAP initialization
uap = torch.zeros((3, 224, 224)).to('cuda')
# For UAP update, set requires_grad True
uap.requires_grad = True

"""### **2-2. Hyperparameter initialization**

If you want to other UAP optimization techniques, feel free to add other hyperparameters you need.
"""

# hyperparameters for UAP generation (FGSM)
max_epsilon=12
step_size=0.7

"""### **2-3. SGD-UAP optimization**

In this practice section, **SGD-UAP** is utilized for UAP optimization.
For fast convergence, we will adopt I-FGSM-based optimization.

SGD-UAP with I-FGSM:

$\delta^{t+1} = \delta^{t} + \alpha\cdot\mathrm{Sign}\{∇_{\delta^t}(\frac{1}{|X_t|}\sum_{x \in X_t}J(x+\delta^t, y))\},$

$\delta^t = \mathrm{Clamp}_{\epsilon}(\delta^t),$

where $X_t$ is the image batch at $t$-th iteration, 
$J(x,y)$ is the loss functions with input image $x$ and label $y$. 
$\delta^t$ is the adversarial perturbation at $t$-th iteration. 
$\mathrm{Clamp}$ restricts the pixel value of the perturbation within the range of $[-\epsilon, \epsilon]$. 
$\alpha$ is the step size, which is a hyperparameter.

We will utilize cross entropy loss as the loss function.
"""

# for epoch in range(5):  # number of epochs
#     for i, data in tqdm(enumerate(train_loader), total=len(train_loader)):
#         inputs, labels = data
#         inputs = inputs.to('cuda')
#         labels = labels.to('cuda')

#         eps = max_epsilon / 255.0
#         alpha = step_size / 255.0

#         # =================== TODO 1 ======================
#         # Prepare adversarial inputs
#         # Add UAP to clean inputs
#         adv_inputs = inputs + uap.unsqueeze(0)
#         # clamp adversarial input with [0,1] range
#         adv_inputs = adv_inputs.clamp(0, 1)
#         # normalize input
#         adv_inputs = normalize(adv_inputs)
#         # ================================================


#         # =================== TODO 1 ======================
#         # Get adversarial model output
#         outputs = model(adv_inputs)
#         # Calculate loss
#         loss = F.cross_entropy(outputs, labels)
#         # ================================================


#         loss.backward()
#         grad = uap.grad.data

#         # =================== TODO 1 ======================
#         # Update UAP with FGSM
#         uap.data = uap.data + alpha * torch.sign(grad)
#         # clamp UAP with epsilon value
#         uap.data = uap.data.clamp(-eps, eps)
#         # ================================================

#         uap.grad.data.zero_()

"""### 2-4. Transferable UAP Generation

You can implement fature-level universal adversarial attack (**PG-UAP**) for transferability.

You can also apply MNI-DTS methods for transferability.

Please modify **basic_attack_core.py** file.
"""

import itertools
import csv
import os

# Hyperparameter tuning
# ======================= TODO 8 =======================
attack_types = ["MNDTS"] 
mus = [1.0] # 모멘텀은 1.0 유지
number_of_si_scales_list = [3, 5]  # 5 주변과 더 작은 값 탐색
di_probs = [0.7, 0.8, 0.9]         # 1.0 배제, 0.8 주변 집중 탐색
di_pad_amounts = [31, 34, 37]      # 34 주변 및 더 큰 값 탐색
di_pad_values = [0]
ti_kernel_sizes = [5, 7]           # 전이성 향상을 위해 커널 사이즈 7 추가 테스트
feature_attacks = [True]
depths = ['layer3', 'layer4']
# ======================================================

# itertools.product를 사용하여 설정한 모든 파라미터 조합을 생성합니다.
hyperparameter_combinations = list(itertools.product(
    attack_types, mus, number_of_si_scales_list, di_probs,
    di_pad_amounts, di_pad_values, ti_kernel_sizes, feature_attacks, depths
))

for (attack_type, mu, number_of_si_scales, di_prob, di_pad_amount, 
     di_pad_value, ti_kernel_size, feature_attack, depth) in hyperparameter_combinations:

    print("\n" + "="*80)
    print(f"[Testing Config] attack_type: {attack_type}, mu: {mu}, SI: {number_of_si_scales}, "
          f"DI_prob: {di_prob}, pad_amount: {di_pad_amount}, pad_value: {di_pad_value}, "
          f"TI_kernel: {ti_kernel_size}, Feature_Attack: {feature_attack}, Depth: {depth}")
    print("="*80 + "\n")

    # UAP initialization
    uap_transfer = torch.zeros((3, 224, 224)).to('cuda')
    # For UAP update, set requires_grad True
    uap_transfer.requires_grad = True

    # hyperparameters for UAP generation (FGSM)
    max_epsilon=12
    step_size=0.7

    target_label = -1

    for epoch in range(5):  # number of epochs
        g = 0
        for i, data in tqdm(enumerate(train_loader), total=len(train_loader)):
            inputs, labels = data
            inputs = inputs.to('cuda')
            labels = labels.to('cuda')

            current_mu = max(apply_mi(attack_type, mu), apply_ni_decay(attack_type, mu))

            ti_conv = None
            if 'T' in attack_type:  # Create smoothing kernel for translation-invariance.
                ti_conv = create_ti_conv(inputs.device, ti_kernel_size)

            model.eval()

            eps = max_epsilon / 255.0  # epsilon in scale [0, 1]
            alpha = step_size / 255.0   # alpha in scale [0, 1]

            x_adv = inputs + uap_transfer.unsqueeze(0)
            x_adv = normalize(x_adv.clamp(0, 1))
            x_clean = normalize(inputs)

            # Calculate ghat from the current adversarial point.
            x_adv_or_nes = apply_ni(attack_type, x_adv, alpha, current_mu, g)

            ghat = calculate_attack_ghat(model, x_adv_or_nes, labels, number_of_si_scales, target_label, attack_type,
                                        di_prob, di_pad_amount, di_pad_value, feature_attack, x_clean, depth)

            # Update g (momentum accumulator)
            ghat = apply_ti(ghat, attack_type, ti_conv)
            g = update_mi_momentum(g, ghat, current_mu)

            # Batch mean of gradient
            g = torch.mean(g, dim=0)

            # Update uap
            pert = alpha * g.sign()
            uap_transfer = uap_transfer + pert

            uap_transfer.data = uap_transfer.data.clamp(-eps, eps)

    # 학습 완료 후 점수 측정
    white_box_score, transfer_score, final_score = evaluate(dataset_val, val_loader, uap_transfer)

    # CSV 기록 로직: 동시 실행 환경을 고려하여 쓰기 직전에 열고 기록 후 즉시 닫습니다.
    csv_filename = "hyperparameter_tuning_results.csv"
    
    # 파일 존재 여부 및 크기를 확인하여 헤더 작성 필요성 판단
    write_header = not os.path.exists(csv_filename) or os.stat(csv_filename).st_size == 0
    
    with open(csv_filename, mode='a', newline='', encoding='utf-8') as f:
        csv_writer = csv.writer(f)
        if write_header:
            csv_writer.writerow([
                'attack_type', 'mu', 'number_of_si_scales', 'di_prob', 'di_pad_amount', 
                'di_pad_value', 'ti_kernel_size', 'feature_attack', 'depth', 
                'White-box SR', 'Transfer SR', 'Final Score'
            ])
        csv_writer.writerow([
            attack_type, mu, number_of_si_scales, di_prob, di_pad_amount, 
            di_pad_value, ti_kernel_size, feature_attack, depth, 
            white_box_score, transfer_score, final_score
        ])
    
    print(f"Result saved for config: {depth}, {di_prob}")